version: "3.8"

services:
  front:
    container_name: front-prod
    image: front-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./src:/app/src
    ports:
      - 3000:80
